2021-02-15 12:54:38,366 ERROR: Exception on /user/edusmith_admin [GET] [in c:\users\never\website\website_dev\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\never\website\website_dev\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\never\website\app\main\routes.py", line 66, in user
    form=form)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\never\website\app\templates\user.html", line 1, in top-level template code
    {% extends "base_wo_ending_script.html" %}
  File "C:\Users\never\website\app\templates\base_wo_ending_script.html", line 3, in top-level template code
    {% extends 'bootstrap_base_wo_script.html' %}
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_base_wo_script.html
2021-02-15 12:55:17,811 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 12:55:17,812 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 12:57:56,464 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 12:57:56,466 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 12:58:44,629 ERROR: Exception on /add_transaction [GET] [in c:\users\never\website\website_dev\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\never\website\website_dev\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\never\website\app\main\routes.py", line 648, in add_transaction
    return render_template('transaction.html', title = 'Transaction', action = "Add", form = form, qir_numbers = None)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\never\website\website_dev\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\never\website\app\templates\transaction.html", line 1, in top-level template code
    {% extends "base_wo_script.html" %}
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base_wo_script.html
2021-02-15 12:59:26,552 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 12:59:26,553 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:00:43,738 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:00:43,738 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:02:22,753 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:02:22,757 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:03:33,418 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:03:33,418 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:04:11,710 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:04:11,711 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:09:21,994 ERROR: Exception on /add_transaction [POST] [in c:\users\never\website\website_dev\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\never\website\website_dev\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\never\website\website_dev\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\never\website\website_dev\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\never\website\app\main\routes.py", line 645, in add_transaction
    array_paid_value, array_this_time_count, preview_filename = save_transaction_changes(transaction, form, new=True)
  File "C:\Users\never\website\app\main\routes.py", line 581, in save_transaction_changes
    db.session.commit()
  File "c:\users\never\website\website_dev\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\never\website\website_dev\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "c:\users\never\website\website_dev\lib\site-packages\sqlalchemy\orm\session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "c:\users\never\website\website_dev\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "C:\Users\never\website\app\models.py", line 39, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "C:\Users\never\website\app\search.py", line 8, in add_to_index
    payload[field] = getattr(model, field)
AttributeError: 'Student' object has no attribute 'firstname'
2021-02-15 13:10:53,788 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:10:53,788 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:11:37,929 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:11:37,929 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:11:42,550 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:11:42,551 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
2021-02-15 13:11:57,112 INFO: Edusmith Sales Portal startup [in C:\Users\never\website\app\__init__.py:119]
2021-02-15 13:11:57,113 INFO: EduSmith Data Server [in C:\Users\never\website\app\__init__.py:131]
